[phases.setup]
nixPkgs = ['python311', 'playwright-driver']

[phases.build]
cmds = ['pip install -r requirements.txt', 'playwright install --with-deps chromium']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'
